# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 472)
        MainWindow.setStyleSheet("QRadioButton {\n"
"  font-size: 20px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.funcInput = QtWidgets.QLineEdit(self.centralwidget)
        self.funcInput.setObjectName("funcInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.funcInput)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.maxInput = QtWidgets.QSpinBox(self.centralwidget)
        self.maxInput.setMinimum(-999999999)
        self.maxInput.setMaximum(999999999)
        self.maxInput.setProperty("value", 100)
        self.maxInput.setObjectName("maxInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxInput)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.minInput = QtWidgets.QSpinBox(self.centralwidget)
        self.minInput.setMinimum(-999999999)
        self.minInput.setMaximum(999999999)
        self.minInput.setProperty("value", -100)
        self.minInput.setObjectName("minInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minInput)
        self.horizontalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 60))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Функция:         y ="))
        self.funcInput.setText(_translate("MainWindow", "x"))
        self.label_2.setText(_translate("MainWindow", "Нижняя граница:"))
        self.label_3.setText(_translate("MainWindow", "Верхняя граница:"))
        self.pushButton.setText(_translate("MainWindow", "Построить"))
from pyqtgraph import PlotWidget
